learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE TAGGING. This must match on the templates
app_name = 'basic_app'

urlpatterns = [
  url(r'^relative/$',views.relative,name='relative'),
  url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text' : 'hello world','number' : 200}
    return render(request,'basic_app/Index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

learning_templates/templates/basic_app/Index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}


{% block body_block %}
      <h1>Welcome to INDEX!</h1>
      <!-- Using template filters to modify information befor displaying to the end user -->
      <!-- <h1>{{ text|upper }}</h1> -->
      <h1>{{ text|cut:'world' }}</h1>
      <h1>{{ number|add:"10" }}</h1>
{% endblock %}

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8" />
  <title>Django level Three</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" />
</head>
<body>
   <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
      </ul>
    </div>
   </nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>
</html>

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
      <h1>Welcome to OTHER!</h1>
      <h2>This is an example of template inheritance!</h1>
{% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to Relative URL Templates!</h1>
      <!-- app_name mentioned in urls.py and the name in urls.py. app_name:url name -->
      <a href="{% url 'basic_app:other' %}" class="btn btn-primary">The Other Page</a>
      <a href="{% url 'admin:index' %}" class="btn btn-primary">Admin Page</a>
      <a href="{% url 'index' %}" class="btn btn-primary">Index Page</a>
    <div>
{% endblock %}